# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- static-website
variables:
  - group: larry-variable-group
pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Class(450668e5-5786-419e-82dd-1901b7404c8f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript:|
      "az storage blob upload-batch --account-name $(STORAGE_ACCOUNT_NAME) --account-key $(STORAGE_ACCOUNT_KEY) --destination '$web' --pattern '*' --source ./"